version: '3'
services:
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/App
      - /App/node_modules/
    ports:
      - "3035:3035"
  rails:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
      - webpacker
    volumes:
      - .:/App
  db:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
    ports:
      - "3307:3307"





