default: &default
  adapter:  mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: password
  host:     db


development:
  <<: *default
  database: <%= ENV['DB_NAME_DEV'] %>
  username: root
  password: password
  host:     db

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>
  host:     localhost

production:
  <<: *default
  database: sample
  username: sample
  password: sample
  host:     sample
